apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: taskmanager
spec:
  type: NodePort
  selector:
    app: taskmanager
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: taskmanager
spec:
  type: NodePort
  selector:
    app: taskmanager
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: taskmanager
spec:
  selector:
    app: taskmanager
  ports:
    - port: 27017
      targetPort: 27017
