name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted  # Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PowerShell (Windows)
        shell: powershell
        run: |
          # Check if PowerShell Core is already installed
          if (-not (Get-Command pwsh -ErrorAction SilentlyContinue)) {
              Write-Host "Installing PowerShell Core..."
              # Download and install PowerShell Core MSI
              $url = "https://github.com/PowerShell/PowerShell/releases/download/v7.3.6/PowerShell-7.3.6-win-x64.msi"
              $msiPath = "$env:TEMP\PowerShell.msi"
              Invoke-WebRequest -Uri $url -OutFile $msiPath
              Start-Process -Wait -FilePath "msiexec.exe" -ArgumentList "/i", "$msiPath", "/quiet", "/qn", "/norestart"
              Remove-Item -Path $msiPath -Force
          }
          pwsh --version
      - name: Check Minikube Version
        shell: pwsh
        run: minikube version

      - name: Set up Docker to use Minikube's environment
        shell: pwsh
        run: |
          Write-Host "Configuring Docker to use Minikube's daemon..."
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Build Backend Docker image
        shell: pwsh
        run: docker build -t your-dockerhub-username/task-manager-backend:latest .

      - name: Build Frontend Docker image
        shell: pwsh
        run: docker build -t your-dockerhub-username/task-manager-frontend:latest ./frontend

      - name: Login to Docker Hub
        shell: pwsh
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images to Docker Hub
        shell: pwsh
        run: |
          docker push your-dockerhub-username/task-manager-backend:latest
          docker push your-dockerhub-username/task-manager-frontend:latest

      - name: Deploy to Minikube
        shell: pwsh
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/mongodb.yaml
          kubectl apply -f k8s/backend.yaml
          kubectl apply -f k8s/frontend.yaml
