name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Use Linux runner (recommended for Minikube)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Minikube and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube version

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Set up Docker to use Minikube's environment
        run: eval $(minikube docker-env)

      - name: Build Backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}//task-manager-backend:latest .

      - name: Build Frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}//task-manager-frontend:latest ./frontend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}//task-manager-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}//task-manager-frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/mongodb.yaml
          kubectl apply -f k8s/backend.yaml
          kubectl apply -f k8s/frontend.yaml
