name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PowerShell
        run: |  
         curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -  
         
         sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
         sudo apt-get update
         sudo apt-get install -y powershell
         
      - name: Check Minikube Version
        shell: pwsh
        run: minikube version

      - name: Set up Docker to use Minikube's environment
        shell: pwsh
        run: |
          Write-Host "Configuring Docker to use Minikube's daemon..."
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Build Backend Docker image
        run: |
          docker build -t your-dockerhub-username/task-manager-backend:latest .

      - name: Build Frontend Docker image
        run: |
          docker build -t your-dockerhub-username/task-manager-frontend:latest ./frontend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push your-dockerhub-username/task-manager-backend:latest
          docker push your-dockerhub-username/task-manager-frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/mongodb.yaml
          kubectl apply -f k8s/backend.yaml
          kubectl apply -f k8s/frontend.yaml
